version: '3'
services:
  ip-geo-api:
    build: ./ip-geo-api
    container_name: ip-geo-api
    ports: 
      - 4000:4000

  ip-geo-ui:
    build: ./ip-geo-ui
    container_name: ip-geo-ui
    ports:
      - 3000:3000